development:
  exception_recipients: [me@example.com]
  exception_email_prefix: '[Waystation] '
  exception_sender_address: '"Error Notifier" <notifier@example.com>'

test:
  exception_recipients: [me@example.com]
  exception_email_prefix: '[Waystation] '
  exception_sender_address: '"Error Notifier" <notifier@example.com>'

staging:
  exception_recipients: [chris.bloom@panopticdev.com]
  exception_email_prefix: '[Waystation] '
  exception_sender_address: '"Error Notifier" <notifier@uta-ridepilot-staging.herokuapp.com>'

production:
  exception_recipients: [me@example.com]
  exception_email_prefix: '[Waystation] '
  exception_sender_address: '"Error Notifier" <notifier@uta-ridepilot-production.herokuapp.com>'
